# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 503)
        self.load_btn = QtWidgets.QPushButton(Form)
        self.load_btn.setGeometry(QtCore.QRect(10, 90, 71, 23))
        self.load_btn.setObjectName("load_btn")
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.save_btn.setObjectName("save_btn")
        self.id_spinBox = QtWidgets.QSpinBox(Form)
        self.id_spinBox.setGeometry(QtCore.QRect(10, 60, 141, 22))
        self.id_spinBox.setObjectName("id_spinBox")
        self.coffeeDB_tableWidget = QtWidgets.QTableWidget(Form)
        self.coffeeDB_tableWidget.setGeometry(QtCore.QRect(0, 150, 341, 192))
        self.coffeeDB_tableWidget.setObjectName("coffeeDB_tableWidget")
        self.coffeeDB_tableWidget.setColumnCount(0)
        self.coffeeDB_tableWidget.setRowCount(0)
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.back_btn.setObjectName("back_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(410, 110, 71, 20))
        self.label_2.setObjectName("label_2")
        self.name_lineEdit = QtWidgets.QLineEdit(Form)
        self.name_lineEdit.setGeometry(QtCore.QRect(410, 140, 113, 20))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(410, 180, 81, 16))
        self.label_3.setObjectName("label_3")
        self.roasting_lineEdit = QtWidgets.QLineEdit(Form)
        self.roasting_lineEdit.setGeometry(QtCore.QRect(410, 200, 113, 20))
        self.roasting_lineEdit.setObjectName("roasting_lineEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(410, 230, 131, 20))
        self.label_4.setObjectName("label_4")
        self.smashed_lineEdit = QtWidgets.QLineEdit(Form)
        self.smashed_lineEdit.setGeometry(QtCore.QRect(410, 260, 113, 20))
        self.smashed_lineEdit.setObjectName("smashed_lineEdit")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(410, 300, 91, 20))
        self.label_5.setObjectName("label_5")
        self.info_textEdit = QtWidgets.QTextEdit(Form)
        self.info_textEdit.setGeometry(QtCore.QRect(410, 320, 171, 51))
        self.info_textEdit.setObjectName("info_textEdit")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(410, 380, 47, 13))
        self.label_6.setObjectName("label_6")
        self.cost_lineEdit = QtWidgets.QLineEdit(Form)
        self.cost_lineEdit.setGeometry(QtCore.QRect(410, 400, 113, 20))
        self.cost_lineEdit.setObjectName("cost_lineEdit")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(410, 430, 47, 13))
        self.label_7.setObjectName("label_7")
        self.volume_lineEdit = QtWidgets.QLineEdit(Form)
        self.volume_lineEdit.setGeometry(QtCore.QRect(410, 450, 113, 20))
        self.volume_lineEdit.setObjectName("volume_lineEdit")
        self.put_pushButton = QtWidgets.QPushButton(Form)
        self.put_pushButton.setGeometry(QtCore.QRect(410, 80, 75, 23))
        self.put_pushButton.setObjectName("put_pushButton")
        self.error_lbl = QtWidgets.QLabel(Form)
        self.error_lbl.setGeometry(QtCore.QRect(376, 50, 161, 20))
        self.error_lbl.setText("")
        self.error_lbl.setObjectName("error_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_btn.setText(_translate("Form", "Загрузить"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
        self.back_btn.setText(_translate("Form", "назад"))
        self.label.setText(_translate("Form", "id:"))
        self.label_2.setText(_translate("Form", "cofee_name:"))
        self.label_3.setText(_translate("Form", "coffee_roasting:"))
        self.label_4.setText(_translate("Form", "smashed_or_completed:"))
        self.label_5.setText(_translate("Form", "taste_info:"))
        self.label_6.setText(_translate("Form", "cost:"))
        self.label_7.setText(_translate("Form", "volume:"))
        self.put_pushButton.setText(_translate("Form", "добавить"))
